version: '3'

services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
